name: NeoPaystub
main: me.neoblade298.neopaystub.NeoPaystub
author: [Neoblade298]
depends: [NeoCore]
version: 1.0
api-version: 1.16
commands:
   paystub:
      description: Main command
      usage: /paystub